name: django-project

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

services:
  project_db:
    restart: always
    image: postgres:16.3-alpine3.20
    container_name: project_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    networks:
      dev-network:
        ipv4_address: 192.168.0.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      dev-network:
        ipv4_address: 192.168.0.3
